services:
  authentication-api:
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    build:
      target: api-dev
    volumes:
      - ./api/prisma/schema.prisma:/usr/authentication/api/prisma/schema.prisma:ro
      - ./api/prisma/seed.ts:/usr/authentication/api/prisma/seed.ts:ro
      - ./api/prisma.config.ts:/usr/authentication/api/prisma.config.ts:ro
      - ./api/src/index.ts:/usr/authentication/api/src/index.ts:ro
      - ./api/src/lib:/usr/authentication/api/src/lib:ro
      - ./api/src/utils:/usr/authentication/api/src/utils:ro
      - ./api/src/routes:/usr/authentication/api/src/routes:ro
      - ./api/src/types:/usr/authentication/api/src/types:ro
    ports:
      - '8080:8080'
