overrides:
  mysql2: "^3.23.1"
  deepmerge-ts: "^8.0.1"
  esbuild: "^0.28.2"

minimumReleaseAgeExclude:
  - "rollup"
  - "@rollup/*"

allowBuilds:
  prisma: true
  "@prisma/engines": true
  esbuild: true
  bcrypt: true
