name: Build Portfolio Multiarch

permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      push_image:
        required: false
        type: boolean
        default: false

env:
  GHCR_REPO: ghcr.io/koptischekerk/auth-api

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    outputs:
      hash: ${{ steps.vars.outputs.hash }}

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Get short commit hash
        id: vars
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v4

      - name: Build AMD64 (local - backend)
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: api-prd
          platforms: linux/amd64
          load: true
          push: false
          tags: local-authentication:api

      - name: Run audit
        run: |
          docker run --rm local-authentication:website \
            sh -c "pnpm i && pnpm audit"

          docker run --rm local-authentication:api \
            sh -c "pnpm i && pnpm audit"

  publish-amd64:
    runs-on: ubuntu-latest
    needs: [build-amd64]
    outputs:
      hash: ${{ needs.build-amd64.outputs.hash }}

    steps:
      - name: Login GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6.0.2

      - name: Build & Push AMD64 - API
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: api-prd
          platforms: linux/amd64
          push: ${{ inputs.push_image }}
          tags: |
            ${{ env.GHCR_REPO }}:api-amd64-${{ needs.build-amd64.outputs.hash }}

  publish-arm64:
    runs-on: ubuntu-24.04-arm
    needs: [build-amd64]
    outputs:
      hash: ${{ needs.build-amd64.outputs.hash }}

    steps:
      - name: Login GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6.0.2

      - name: Build & Push ARM64 - API
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: api-prd
          platforms: linux/arm64
          push: ${{ inputs.push_image }}
          tags: |
            ${{ env.GHCR_REPO }}:api-arm64-${{ needs.build-amd64.outputs.hash }}

  publish:
    runs-on: ubuntu-latest
    needs: [publish-amd64, publish-arm64]
    if: ${{ inputs.push_image }}

    steps:
      - name: Login GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v4

      - name: Publish the multi-tag images
        run: |
          HASH=${{ needs.publish-amd64.outputs.hash }}

          # Backend
          docker buildx imagetools create \
            -t ${{ env.GHCR_REPO }}:api \
            -t ${{ env.GHCR_REPO }}:api-$HASH \
            -t ${{ env.GHCR_REPO }}:api-latest \
            -t ${{ env.GHCR_REPO }}:api-latest-$HASH \
            ${{ env.GHCR_REPO }}:api-amd64-$HASH \
            ${{ env.GHCR_REPO }}:api-arm64-$HASH
